---
abstract: 'Mojolicious Plugin for Rendering Perl Code Using PPI'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-PPI
provides:
  Mojolicious::Plugin::PPI:
    file: lib/Mojolicious/Plugin/PPI.pm
    version: 0.04
requires:
  File::ShareDir: 1.00
  Mojolicious: 2.0
  PPI::HTML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
